# Generated by Django 6.0.3 on 2026-03-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=100, unique=True)),
                ("url", models.URLField(max_length=500)),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.PositiveIntegerField()),
                ("mileage", models.PositiveIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "price_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=50)),
                ("fuel_type", models.CharField(blank=True, max_length=50)),
                ("transmission", models.CharField(blank=True, max_length=50)),
                ("engine_size", models.CharField(blank=True, max_length=20)),
                ("body_type", models.CharField(blank=True, max_length=50)),
                ("drive_type", models.CharField(blank=True, max_length=20)),
                ("doors", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("seats", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("inspection_date", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(blank=True, max_length=100)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("image_urls", models.JSONField(default=list)),
                ("raw_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scraped_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["-scraped_at"],
                "indexes": [
                    models.Index(
                        fields=["brand", "model"], name="cars_car_brand_812f04_idx"
                    ),
                    models.Index(fields=["year"], name="cars_car_year_fc6735_idx"),
                    models.Index(fields=["price"], name="cars_car_price_f6b08b_idx"),
                    models.Index(
                        fields=["mileage"], name="cars_car_mileage_f4d08e_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="cars_car_created_f3c7e2_idx"
                    ),
                ],
            },
        ),
    ]
